### ISSUE TITLE
wrong attribute.

### ISSUE THREAD

**Issue by ghost** [fvrmatteo/TritonASTLLVMIRTranslator#1]
this should be fixed cause LLVM class doesn't have an 'AlwaysInline' Attribute ; )

[Translator.cpp#L301](https://github.com/fvrmatteo/TritonASTLLVMIRTranslator/blob/master/Translator.cpp#L301)
[Translator.cpp#L954](https://github.com/fvrmatteo/TritonASTLLVMIRTranslator/blob/master/Translator.cpp#L954)

**Comment by fvrmatteo** [comment]
Hey, **llvm::Attribute::AlwaysInline** is a valid attribute with all the LLVM versions I tried, are you sure it is invalid now? With which LLVM version did you try?

**Comment by ghost** [comment]
i tried it under LLVM 13.0.0 , i had to remake the build configs cause the scripts included are deprecated .

**Comment by fvrmatteo** [comment]
OK, there's no plan to update the code to support newer LLVM versions out of the box, as the code only serves as an example. Feel free to create a PR to update it to build with LLVM 13.
